name: ui_challenge_plant_shop
description: Plants Shop App UI

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.5
  flutter_bloc: ^8.0.0
  intl: ^0.18.1
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  plants_repository:
    path: packages/plants_repository
  flutter_carousel_widget: ^2.1.0
  google_fonts: ^6.1.0
  meta: ^1.9.1
  auto_size_text: ^3.0.0
  peanut: ^5.0.0
  flutter_native_splash: ^2.3.4
#  device_preview: ^1.1.0
#
#dependency_overrides:
  device_preview:
    git:
      url: https://github.com/bradrushworth/flutter_device_preview.git
      path: device_preview
      ref: master
#  device_preview: ^1.1.0
  # device_frame: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/plants.json

flutter_native_splash:
    color: "#ffffff"
    image: assets/images/splash.png
    android: true
    ios: true
    android_gravity: center
    ios_content_mode: center
